name: appliance_tracker
description: Flutter app for appliance energy tracking
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.1
  http: ^1.1.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  fl_chart: ^1.1.1
  path: ^1.8.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: MyCustomFont
      fonts:
        - asset: assets/fonts/nothing-font-5x7.ttf
